export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_CURRENT_STOCK = 'SET_CURRENT_STOCK'
export const UPDATE_STOCK = 'UPDATE_STOCK'
export const GET_STOCKS = 'GET_STOCKS'

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';

export const LOADING_UI = 'LOADING_UI'